In [28]:
import pandas as pd

train_df = pd.read_csv("../data/processed/train_balanced.csv")
test_df = pd.read_csv("../data/processed/test_data.csv")

train_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,loan_status
0,0.890718,0.998537,-1.008528,-0.092646,-0.088677,-0.850759,1.131102,-0.235163,-1.137306,-0.444440,-0.736827,-0.667204,-0.008765,-1.334094,-0.548034,1
1,0.301107,0.998537,0.991544,0.265460,0.180218,1.243433,0.194245,0.107588,0.785995,-0.048387,-0.396795,0.124127,-0.176417,-0.220322,-0.304594,1
2,-0.288503,0.998537,0.991544,1.089102,0.807638,1.243433,0.795684,2.319895,1.747645,1.304793,0.716035,1.898157,-0.388339,1.348950,0.316427,1
3,-0.288503,-1.001465,0.991544,-0.235888,-0.133492,-0.850759,1.217848,0.902149,-0.175656,-0.015383,0.066884,0.263774,0.293316,0.732430,-0.296313,1
4,1.480328,0.998537,-1.008528,0.516133,1.087736,-0.501727,1.038573,-0.063787,1.060752,0.061628,1.179714,0.444797,1.395190,-0.890208,-0.486760,1

In [29]:
X_train = train_df.drop("loan_status", axis=1)
y_train = train_df["loan_status"]

X_test = test_df.drop("loan_status", axis=1)
y_test = test_df["loan_status"]

In [33]:
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [31]:
log_model = LogisticRegression()

log_model.fit(X_train, y_train)

log_pred = log_model.predict(X_test)

In [34]:
print("Logistic Regression Accuracy:", accuracy_score(y_test, log_pred))
print(classification_report(y_test, log_pred))
print(confusion_matrix(y_test, log_pred))

Logistic Regression Accuracy: 0.9203747072599532
              precision    recall  f1-score   support

           0       0.88      0.91      0.90       323
           1       0.95      0.92      0.94       531

    accuracy                           0.92       854
   macro avg       0.91      0.92      0.92       854
weighted avg       0.92      0.92      0.92       854

[[295  28]
 [ 40 491]]

In [35]:
svm_model = SVC()

svm_model.fit(X_train, y_train)

svm_pred = svm_model.predict(X_test)

In [41]:
print("SVM Accuracy:", accuracy_score(y_test, svm_pred))
print(classification_report(y_test, svm_pred))
print(confusion_matrix(y_test, svm_pred))

SVM Accuracy: 0.9426229508196722
              precision    recall  f1-score   support

           0       0.91      0.94      0.93       323
           1       0.96      0.95      0.95       531

    accuracy                           0.94       854
   macro avg       0.94      0.94      0.94       854
weighted avg       0.94      0.94      0.94       854

[[303  20]
 [ 29 502]]

In [38]:
knn_model = KNeighborsClassifier(n_neighbors=5)

knn_model.fit(X_train, y_train)

knn_pred = knn_model.predict(X_test)

In [39]:
print("KNN Accuracy:", accuracy_score(y_test, knn_pred))
print(classification_report(y_test, knn_pred))

KNN Accuracy: 0.8782201405152225
              precision    recall  f1-score   support

           0       0.81      0.89      0.85       323
           1       0.93      0.87      0.90       531

    accuracy                           0.88       854
   macro avg       0.87      0.88      0.87       854
weighted avg       0.88      0.88      0.88       854

In [40]:
results = pd.DataFrame({
    "Model": ["Logistic Regression", "SVM", "KNN"],
    "Accuracy": [
        accuracy_score(y_test, log_pred),
        accuracy_score(y_test, svm_pred),
        accuracy_score(y_test, knn_pred)
    ]
})

results

                 Model  Accuracy
0  Logistic Regression  0.920375
1                  SVM  0.942623
2                  KNN  0.878220

Model Evaluation (SVM)

The Support Vector Machine (SVM) model achieved an accuracy of approximately
94.26% on the test dataset. The model demonstrates strong performance across
both classes with high precision, recall, and F1-scores.

The confusion matrix indicates that most loan approvals and rejections are
correctly predicted, with only a small number of misclassifications.
Overall, SVM provides a reliable classification model for predicting loan
approval outcomes.

## Hyperparamter Tunning

In [42]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

In [43]:
param_grid = {
    "C": [0.1, 1, 10, 100],
    "kernel": ["linear", "rbf"],
    "gamma": ["scale", "auto"]
}

In [44]:
grid = GridSearchCV(
    SVC(),
    param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

In [45]:
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SVC(), n_jobs=-1,
             param_grid={'C': [0.1, 1, 10, 100], 'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'rbf']},
             scoring='accuracy')

In [46]:
print("Best Parameters:", grid.best_params_)

Best Parameters: {'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}

In [47]:
best_svm = grid.best_estimator_

In [49]:
y_pred = best_svm.predict(X_test)

In [50]:
from sklearn.metrics import accuracy_score, classification_report

print("Tuned SVM Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Tuned SVM Accuracy: 0.9566744730679156
              precision    recall  f1-score   support

           0       0.96      0.93      0.94       323
           1       0.96      0.97      0.97       531

    accuracy                           0.96       854
   macro avg       0.96      0.95      0.95       854
weighted avg       0.96      0.96      0.96       854

In [51]:
import pickle

pickle.dump(best_svm, open("../models/svm_model.pkl", "wb"))

### After hyperparameter tuning, the Support Vector Machine (SVM) model achieved an accuracy of 95.67% on the test dataset. The model demonstrates strong performance across both classes with balanced precision, recall, and F1-scores. These results indicate that the tuned SVM model effectively captures the relationship between financial attributes and loan approval outcomes.